version: 2
jobs:
  build:
    machine:
      enabled: true
      node:
        version: 9.3.0
    environment:
      DOCKER_NAME: quay.io/matt_whitaker/mattwhitaker.name
    branches:
      only:
        - develop
        - master
    steps:
      - checkout

      - run:
          name: install
          command: npm install

      - run:
          name: build
          command: ./bin/build.sh

      - run:
          name: test
          command: NODE_ENV=test npm test

      - run:
          name: docker login
          command: docker login -u $QUAY_BOT_USER -p $QUAY_BOT_PASS quay.io

      - run:
          name: docker build
          command: docker build -t $DOCKER_NAME .

      - run:
          name: docker tag
          command: ./bin/docker-tag.sh

      - run:
          name: docker push
          command: ./bin/docker-push.sh

      - run:
          name: static deploy
          command: ./bin/static-deploy.sh
  test:
    machine:
      enabled: true
      node:
        version: 9.3.0
    environment:
      DOCKER_NAME: quay.io/matt_whitaker/mattwhitaker.name
    branches:
      ignore:
        - develop
        - master
    steps:
      - checkout

      - run:
          name: install
          command: npm install

      - run:
          name: build
          command: ./bin/build.sh

      - run:
          name: test
          command: NODE_ENV=test npm test