defaults:
  working_directory: /tmp

version: 2
jobs:
  build:
    machine:
      enabled: true
      node:
        version: 9.3.0
    steps:
      - checkout

      - run:
          name: install
          command: npm install

      - run:
          name: build
          command: ./bin/build.sh

      - run:
          name: test
          command: NODE_ENV=test npm test

      - run: mkdir workspace
      - run: cp -R lib workspace/lib
      - run: cp -R bin workspace/bin

      - persist_to_workspace:
          root: workspace
          paths:
            - lib
            - bin

  publish-docker:
    environment:
      DOCKER_NAME: quay.io/matt_whitaker/mattwhitaker.name
    machine:
      enabled: true
      node:
        version: 9.3.0
    steps:
      - attach_workspace:
          at: workspace

      - run:
          name: docker login
          command: docker login -u $QUAY_BOT_USER -p $QUAY_BOT_PASS quay.io

      - run:
          name: docker build
          command: docker build -t $DOCKER_NAME .

      - run:
          name: docker tag
          command: ./bin/docker-tag.sh

      - run:
          name: docker push
          command: ./bin/docker-push.sh

  deploy-static:
    machine:
      enabled: true
      node:
        version: 9.3.0
    steps:
      - attach_workspace:
          at: workspace

      - run: ls -a
      - run: ls tmp -a
      - run: ls tmp/workspace -a
      - run: ls workspace -a

      - run:
          name: static deploy
          command: ./bin/static-deploy.sh

workflows:
  version: 2
  deploy-static:
    jobs:
      - build
      - deploy-static:
          requires:
            - build
  publish-docker:
    jobs:
      - build
      - publish-docker:
          requires:
            - build