# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
# ...

version: 2
jobs:
  build:
    environment:
      DOCKER_NAME: quay.io/matt_whitaker/mattwhitaker.name
    machine:
      enabled: true
      node:
        version: 9.3.0
    branches:
      only:
        - master
        - develop
    steps:
      - checkout
      - run: npm install

      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              NODE_ENV=production npm run build
            else
              NODE_ENV=qa npm run build
            fi

      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              NODE_ENV=production \
              AWS_CLOUDFRONT_DISTRIBUTION_ID=$AWS_CLOUDFRONT_DISTRIBUTION_ID_PROD \
              AWS_S3_BUCKET=$AWS_S3_BUCKET_PROD \
              npm run build
            else
              NODE_ENV=qa \
              AWS_CLOUDFRONT_DISTRIBUTION_ID=$AWS_CLOUDFRONT_DISTRIBUTION_ID_QA \
              AWS_S3_BUCKET=$AWS_S3_BUCKET_QA \
              npm run deploy
            fi


      - run: docker login -u $QUAY_BOT_USER -p $QUAY_BOT_PASS quay.io
      - run: docker build -t $DOCKER_NAME .
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag $DOCKER_NAME $DOCKER_NAME:master
              docker tag $DOCKER_NAME $DOCKER_NAME:$VERSION
            else
              docker tag $DOCKER_NAME $DOCKER_NAME:develop
            fi
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push $DOCKER_NAME:master
              docker push $DOCKER_NAME:$VERSION
            else
              docker push $DOCKER_NAME:develop
            fi