
version: 2
jobs:
  test:
    machine:
      enabled: true
      node:
        version: 9.3.0
    steps:
      - checkout

      - run:
          name: install
          command: npm install

      - run:
          name: build
          command: npx build

      - run:
          name: test
          command: NODE_ENV=test npm test

      - run:
          name: create workspace
          command: mkdir -p workspace

      - run:
          name: copy to workspace
          command: cp -R {lib,node_modules} workspace

      - persist_to_workspace:
          root: workspace
          paths:
            - lib
            - node_modules

  publish-docker:
    machine:
      enabled: true
      node:
        version: 9.3.0
    environment:
      DOCKER_NAME: quay.io/matt_whitaker/mattwhitaker.name
    steps:
      - checkout

      - attach_workspace:
          at: workspace

      - run:
          name: copy from workspace
          command: cd workspace && cp -R * ..

      - run:
          name: docker login
          command: docker login -u $QUAY_BOT_USER -p $QUAY_BOT_PASS quay.io

      - run:
          name: docker build
          command: docker build -t $DOCKER_NAME .

      - run:
          name: docker tag
          command: npx docker-tag

      - run:
          name: docker push
          command: npx docker-push

  deploy-static:
    machine:
      enabled: true
      node:
        version: 9.3.0
    steps:
      - checkout

      - attach_workspace:
          at: workspace

      - run: cd workspace && cp -R * ..

      - run:
          name: static deploy
          command: npx static-deploy

workflows:
  version: 2
  deploy:
    jobs:
      - test
      - deploy-static:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
                - master
      - publish-docker:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
                - master
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - develop
                - master
