
version: 2
jobs:
  test:
    machine:
      enabled: true
      node:
        version: 9.3.0
    steps:
      - checkout

      - run:
          name: install
          command: npm install

      - run:
          name: build
          command: ./bin/build.sh

      - run:
          name: test
          command: NODE_ENV=test npm test


      - run: mkdir -p workspace
      - run: cp -R {lib,Dockerfile,bin} workspace
      - persist_to_workspace:
          root: workspace
          paths:
            - lib
            - Dockerfile
            - bin

  deploy:
    machine:
      enabled: true
      node:
        version: 9.3.0
    environment:
      DOCKER_NAME: quay.io/matt_whitaker/mattwhitaker.name
    steps:
      - checkout

      - attach_workspace:
          at: workspace

      - run: cd workspace && cp * ..

      - run:
          name: docker login
          command: docker login -u $QUAY_BOT_USER -p $QUAY_BOT_PASS quay.io

      - run:
          name: docker build
          command: docker build -t $DOCKER_NAME .

      - run:
          name: docker tag
          command: ./bin/docker-tag.sh

      - run:
          name: docker push
          command: ./bin/docker-push.sh

      - run:
          name: static deploy
          command: ./bin/static-deploy.sh

workflows:
  version: 2
  deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
                - master
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - develop
                - master
