
version: 2
jobs:
  build and test:
    machine:
      enabled: true
      node:
        version: 12.2.0
    steps:
      - checkout

      - run:
          name: install
          command: npm install

      - run:
          name: build
          command: npm build

      - run:
          name: test
          command: NODE_ENV=test npm test

      - run:
          name: create workspace
          command: mkdir -p workspace

      - run:
          name: copy to workspace
          command: cp -R {lib,node_modules} workspace

      - persist_to_workspace:
          root: workspace
          paths:
            - lib
            - node_modules

  deploy:
    machine:
      enabled: true
      node:
        version: 12.2.0
    steps:
      - checkout

      - attach_workspace:
          at: workspace

      - run: cd workspace && cp -R * ..

      - run:
          name: deploy
          command: npm run deploy

workflows:
  version: 2
  deploy:
    jobs:
      - build and test
      - deploy:
          requires:
            - build and test
          filters:
            branches:
              only:
                - develop2
                - develop
                - master
  build and test:
    jobs:
      - build and test:
          filters:
            branches:
              ignore:
                - develop2
                - develop
                - master
