# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
# ...

version: 2
jobs:
  build:
    machine:
      enabled: true
      node:
        version: 9.3.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
      - deploy:
          name: Deploy updates
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              export NODE_ENV=production
              export AWS_CLOUDFRONT_DISTRIBUTION_ID=$AWS_CLOUDFRONT_DISTRIBUTION_ID_PROD
              export AWS_S3_BUCKET=$AWS_S3_BUCKET_PROD
              npm run deploy
              echo "Deployed to production"
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              export NODE_ENV=qa
              export AWS_CLOUDFRONT_DISTRIBUTION_ID=$AWS_CLOUDFRONT_DISTRIBUTION_ID_QA
              export AWS_S3_BUCKET=$AWS_S3_BUCKET_QA
              npm run deploy
              echo "Deployed to QA"
            else
              echo "No deployment performed"
            fi