name: Build, Test, and Deploy
run-name: "Build, Test, and Deploy"
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
#      - uses: actions/setup-python@v4
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: www-assets
          path: packages/www/dist
  Test:
    runs-on: ubuntu-latest
    needs: ["Build"]
    steps:
      - run: echo "No tests yet..."

  Deploy:
    runs-on: ubuntu-latest
    needs: ["Build", "Test"]
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: aws s3 sync packages/www/dist s3://dev.mattwhitaker.name
      - run: echo "done?"