name: Build, Test, and Deploy (Prod)
run-name: "Build, Test, and Deploy (Prod)"
on: 
  push:
    branches:
      - mainline
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: www-assets
          path: packages/www/dist
          
  Test:
    runs-on: ubuntu-latest
    needs: ["Build"]
    steps:
      - run: echo "No tests yet..."

  Deploy:
    runs-on: ubuntu-latest
    needs: ["Build", "Test"]
    environment: "prod"
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-session-name: WWWDeploySession
      - uses: actions/download-artifact@v4
        with:
          name: www-assets
          path: packages/www/dist
      - run: aws s3 sync --delete --acl public-read packages/www/dist s3://${{ secrets.WWW_AWS_S3_BUCKET }}
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.WWW_AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/" >/dev/null
