name: Build, Test, and Deploy (Dev)
run-name: "Build, Test, and Deploy (Dev)"

on:
  push:
    branches:
      - develop
      - mainline

env:
  NODE_VERSION: 18

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: npm run build
      - run: npm run pack
      - uses: actions/upload-artifact@v4
        with:
          name: dev
          path: dist
          
  Test:
    runs-on: ubuntu-latest
    needs: ["Build"]
    steps:
      - run: echo "No tests yet..."

  Deploy:
    needs: ["Build", "Test"]
    uses: matt-whitaker/aws-static-site/.github/workflows/deploy-static-site.yaml@1.0.0
    with:
      environment: "dev"
      aws_default_region: "us-west-2"
      artifact_name: "dev"
      artifact_path: "dist"
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      aws_s3_bucket: ${{ secrets.WWW_AWS_S3_BUCKET }}
      aws_cloudfront_distribution_id: ${{ secrets.WWW_AWS_CLOUDFRONT_DISTRIBUTION_ID }}