name: Build and Test

on: [push]

jobs:
  build and test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 13.6.0
    - name: Run npm install, build, and test
      run: |
        npm ci
        npm test
        npm run build --if-present
      env:
        CI: true
