name: Generate PDFs
run-name: Generate PDFs

on:
  push:
    branches:
      - _never_

env:
  NODE_VERSION: 18

jobs:
  Generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: npm start -w packages/resume &
      - id: wait-for-server
        run: |
          until curl -s http://localhost:8080; do
            sleep 2
          done
      - run: npm run generate:all -w packages/resume
      - uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: packages/resume/dist/pdf
